spring:
  application:
    name: zuul
    rabbitmq:
    host: 192.168.234.133
    port: 5672
    username: admin
    password: admin
    sleuth:
    sampler:
      probability: 0.1  
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
ribbon: #默认
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix: #默认
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500